version: "3.9"

networks:
  adri:
    driver: bridge

services:
  ################################################################################################
  # DATABASE MYSQL
  ################################################################################################
  adri-db:
    container_name: adri-db
    image: "mysql/mysql-server:8.0.27"
    command: mysqld --sql_mode="" --slow_query_log=1 --slow_query_log_file=/var/log/mysql/mysql-slow.log --long_query_time=0.2
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=forge
    volumes:
      - ./database/log:/var/log/mysql
    ports:
      - "3306:3306"
    networks:
      - adri
    healthcheck:
      test:
        ["CMD-SHELL", "MYSQL_PWD=healthcheck mysqladmin ping -u healthcheck"]
  ################################################################################################
  # GESTIONALE LAMP
  ################################################################################################
  adri-app:
    container_name: adri-app
    build: 
      context: ./
      dockerfile: Dockerfile
    image: adri-app
    entrypoint: ./docker-compose/entrypoint.sh
    networks:
      - adri
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      adri-db:
        condition: service_healthy
  # NGNIX
  adri-nginx:
    image: nginx:1.17-alpine
    container_name: adri-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - adri
